# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEOeZE8shCN5qDIWudGP6CzigDhK2_Gp
"""

import math

class Vector:
    def _init_(self, coordenada_x, coordenada_y):
        self.x = coordenada_x
        self.y = coordenada_y
        self.magnitud = math.sqrt(self.x * 2 + self.y * 2)
        self.angulo = math.atan2(self.y, self.x)

    def _str_(self):
        respuesta = "( " + str(self.x) + " , " + str(self.y) + " )"
        return respuesta

    def _sub_(self, otra):
        respuesta = Vector(self.x - otra.x, self.y - otra.y)
        return respuesta

    def _add_(self, otra):
        respuesta = Vector(self.x + otra.x, self.y + otra.y)
        return respuesta

    def escalar(self, otra):
        return self.x * otra.x + self.y * otra.y

    def producto_punto(self, otro):
        resultado = self.x * otro.x + self.y * otro.y
        return resultado

    def producto_cruz(self, otro):
        respuesta = self.x * otro.y - self.y * otro.x
        return respuesta

print("Ingrese el vector posicion")
x_1 = float(input("Componente X: " ))
y_1 = float(input("Componente Y: " ))

print("Ingrese el vector de momento lineal")
x_2 = float(input("Componente X: " ))
y_2 = float(input("Componente Y: " ))

print("El resultado de los vectores es:")
vec_1 = Vector(x_1, y_1)
vec_2 = Vector(x_2, y_2)
print(vec_1)
print(vec_2)
momento = abs(vec_1.producto_cruz(vec_2))
print("El momento angular es: ", momento)

if momento == 0:  # agregado el nombre de la variable "momento"
    print("Los vectores velocidad angular y momento lineal son paralelos entre si, por lo tanto el momento angular es nulo.")

productopunto = (vec_1.producto_punto(vec_2))

if productopunto == 0:  # agregado el nombre de la variable "productopunto"
    print("Los vectores velocidad angular y momento lineal son ortogonales entre si, por lo tanto el momento angular es maximo.")

print("Ingrese la masa")
m = float(input("masa: " ))

print("Ingrese la radio")
r = float(input("radio: " ))

escalar1 = m
escalar2 = r

momentodeinercia = escalar1 * escalar2 * escalar2  # Multiplicación por la masa y el radio al cuadrado
print("El momento de inercia es: ", momentodeinercia)


velocidaangular = (momento / (momentodeinercia))
print("La velocidad angular es: ", velocidaangular)